title: "若朴若谷"
author: "舒信"
description:
  "Page Guo All Rights Reserved.<br/>
  Theme Powered By <a href="https://github.com/niklasbuschmann/con trast"><i>Jekyll Theme Contrast</i></a>""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Subfolders
include:
  -['research']

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", file: "index.html"}
  - {title: "Research", file: "Research.md"}
  - {title: "About", file: "About.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:guopeiqicharles@foxmail.com"}
  - {title: Github, icon: github, url: "https://shuxinpage.github.io/"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

